### ISSUE TITLE
Support 128 bit hash

### ISSUE THREAD

**Issue by sherry-ger** [logstash-plugins/logstash-filter-fingerprint#32]
For large volume of documents, 32 bit hash won't be large enough to support the creation of unique IDs.  Please provide 128 bit hash support.

**Comment by jakelandis** [comment]
@sherry-ger - MD5 is 128 bit , and all the SHA functions are larger then 32 bit too. 

Is this specifically for the mumur3 hash ?

**Comment by mbarretta** [comment]
+1
@jakelandis benefit for murmur3 is speed when a cryptographic hash is not necessary.
