### ISSUE TITLE
fingerprint punctuation doesn't just leave punctuation

### ISSUE THREAD

**Issue by suyograo** [logstash-plugins/logstash-filter-fingerprint#4]
The PUNCTUATION method of the fingerprint filter isn't described on the fingerprint docs, but the behaviour matches the old punct filter (which is understandable).

That's described as "Strip _everything but punctuation_ from a field and store the remainder in the a separate field" but it's not true because the logic used actually only stripes out US-ASCII letters and digits, plus space and tab.

So it doesn't do what it describes for non-ASCII inputs such as letters with accents.

I"m not familiar with Ruby but the fix might be to use the \[^\[:punct:]] regex, assuming that behaves properly for unicode strings and uses the unicode punctuation property.

You'd need to give this a new method name, perhaps "PUNCT".

Would also be nice to give an example output in the docs for each of the methods.

moved from https://logstash.jira.com/browse/LOGSTASH-2251

**Comment by jordansissel** [comment]
+1 on this bug

**Comment by purbon** [comment]
This is fix in #5, feel free to review.
