### ISSUE TITLE
"concatenate_sources" doc explanation doesn't match the behaviour 

### ISSUE THREAD

**Issue by kaisecheng** [logstash-plugins/logstash-filter-fingerprint#59]
[doc](https://www.elastic.co/guide/en/logstash/current/plugins-filters-fingerprint.html#plugins-filters-fingerprint-concatenate_sources) is not accurate. 
>  If false and multiple source fields are given, the target field will be an array with fingerprints of the source fields given.

correct: The target field will be a **single** fingerprint of the last source fields.

```
fingerprint {
  source => ["user_id", "siblings", "birthday"]
}
```
The above example will give a single `"fingerprint" => "6b6390a4416131f82b6ffb509f6e779e5dd9630f"` which is computating from `birthday` (because it is the last source field)

The next example will give an array of fingerprint, assuming `siblings` is an array `["big brother", "little sister", "little brother"]`

```
fingerprint {
  source => ["user_id", "siblings"]
}
```
the output is
```
 "fingerprint" => [
        [0] "fdfeb16f096983ada02db49d46a8154475d700ae",
        [1] "a85ed0f0a425b690a75fcbab6c256837bac04dad",
        [2] "6b6390a4416131f82b6ffb509f6e779e5dd9630f"
    ],
```

Related SDH: https://github.com/elastic/sdh-logstash/issues/571#issuecomment-777700706

**Comment by karenzone** [comment]
Closed with fix: #60
