### ISSUE TITLE
Fingerprint doesn't capture millisecond difference in timestamps

### ISSUE THREAD

**Issue by buddyp450** [logstash-plugins/logstash-filter-fingerprint#9]
Copied from https://discuss.elastic.co/t/fingerprint-unable-to-fingerprint-timestamp/29855

The following logstash configuration will result in indentical fingerprints for messages with @timestamp field differing by their milliseconds, like:

2015-09-22T00:00:00.000Z

vs.

2015-09-22T00:00:00.001Z

```
filter {
  date {
    match => ['timestamp', 'ISO8601']
  }
  fingerprint {
    method => 'MD5'
    key => '00000000'
    target => 'fingerprint'
    source => [ '@timestamp' ] #problem
  }
}

output {
  stdout {
    codec => 'json'
  }
  elasticsearch {
    host => '127.0.0.1'
    cluster => 'logstash'
    document_id => '%{fingerprint}'
  }
}
```

edit: to add this is in logstash version 1.4.3

**Comment by guyboertje** [comment]
The timestamp should be special cased - the standard `to_s` output does not include millseconds.

**Comment by lucabelluccini** [comment]
I've started to add a test for it and try to implement a fix.
